name = "LaskaPlot"
uuid = "47311fc3-b5d5-4c44-b326-9386a1fd4d79"
authors = ["Elias Sj√∂lin <elias.sjolin@gmail.com>"]
version = "1.0.0-DEV"

[deps]
LaskaCore = "9ad29ce2-7782-4744-ab48-6ef9cc0286bb"
LaskaStats = "de767ba9-e829-4e7c-bf82-062dc00bf36c"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
MakieCore = "20f20a25-4f0e-4fdf-b5d1-57303727442b"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"

[compat]
Revise = "3"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
